In [4]:
#Q1

import numpy as np

def compute_vector_length(vector):
    norm = np.sqrt(np.sum([v**2 for v in vector]))
    return norm

vector = np.array([-2,4,9,21])
result = compute_vector_length([vector])
print(round(result,2))

23.28


In [5]:
#Q2

def compute_dot_product(vector_1, vector_2):
    result = np.dot(vector_1,vector_2)
    return result

v1 = np.array([0,1,-1,2])
v2 = np.array([2,5,1,0])
result = compute_dot_product(v1,v2)
print(result) #4


4


In [6]:
#Q3

x = np.array([[1,2],
              [3,4]])
k = np.array([1,2])
print('result \n', x.dot(k)) #[5 11]


result 
 [ 5 11]


In [7]:
#Q4

x = np.array([[-11,2],
              [3,-4]])
k = np.array([1,2])
print('result \n', x@k) #[-7 -5]


result 
 [-7 -5]


In [8]:
#Q5

def matrix_multi_vector(m, v):
    result = m @ v
    return result

m = np.array([[-1,1,1],
              [0,-4,9]])
v = np.array([0,2,1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [9]:
#Q6

def matrix_multi_matrix(m1,m2):
    result = m1 @ m2
    return result

m1 = np.array ([[0 , 1, 2], [2, -3, 1]])
m2 = np.array ([[1 , -3] ,[6 , 1], [0, -1]])
result = matrix_multi_matrix (m1 , m2)
print(result)


[[  6  -1]
 [-16 -10]]


In [10]:
#Q7

m1 = np.eye(3)
m2 = np.array([[1,1,1],
               [2,2,2],
               [3,3,3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [11]:
#Q8

m1 = np.eye(2)
m1 = np.reshape(m1, (-1,4))[0]
m2 = np.array([[1,1,1,1],
               [2,2,2,2],
               [3,3,3,3],
               [4,4,4,4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [12]:
#Q9

m1 = np.array([[1,2],[3,4]])
m1 = np.reshape(m1, (-1,4), "F")[0]
m2 = np.array([[1,1,1,1],
               [2,2,2,2],
               [3,3,3,3],
               [4,4,4,4]])
result = m1@m2
print(result)

[29 29 29 29]


In [13]:
#Q10

def inverse_matrix(matrix):
    inv_matrix = np.linalg.inv(matrix)
    return inv_matrix

m1 = np.array([[1,2], [3,4]])
result = inverse_matrix(m1)
print(result)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
#Q11

def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrix = np.array([[0.9,0.2],
                   [0.1,0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [15]:
#Q12

def compute_cosine(x,y):
    result = np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
    return result

x = np.array([1,2,3,4])
y = np.array([1,0,3,0])
result = compute_cosine(x,y)
print(round(result,3))

0.577
